logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR

management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    show-actuator: true
  show-actuator: true
  cache:
    disabled: true
server:
  forward-headers-strategy: framework
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8943
aws:
  api-gateway: https://${AWS_API_GATEWAY_ID}.execute-api.${AWS_REGION}.amazonaws.com
  region: ${AWS_REGION}
  cognito:
    client-id: ${CLIENT_CREDENTIALS_ID}
    client-secret: ${CLIENT_CREDENTIALS_SECRET}
    domain: ${CLIENT_DOMAIN}
    user-pool-id: ${AWS_COGNITO_USER_POOL_ID}
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}/is-my-burguer?retryWrites=true&w=majority&appName=is-my-burguer-mongodb

  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${CLIENT_CREDENTIALS_ID}
        provider:
          cognito:
            authorization-uri: https://${aws.cognito.domain}.auth.${aws.region}.amazoncognito.com/oauth2/authorize
            token-uri: https://${aws.cognito.domain}.auth.${aws.region}.amazoncognito.com/oauth2/token
            user-info-uri: https://${aws.cognito.domain}.auth.${aws.region}.amazoncognito.com/oauth2/userInfo
            jwk-set-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.user-pool-id}/.well-known/jwks.json
            issuerUri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.user-pool-id}
            user-name-attribute: username
            authorization-grant-type: authorization_code

        resourceserver:
          cognito:
            jws-algorithms: RS256
            jwk-set-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.user-pool-id}/.well-known/jwks.json
            issuer-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.user-pool-id}

  # Quartz
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: true